(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], day=()=>new Date().toISOString().slice(0,10);
const GIFT=window.FITLOG_CONFIG||{};
const DEFAULT={profile:{name:'',sex:'',birthYear:'',height:'',weight:'',target:'',bodyFat:'',muscle:'',trainingDays:4,calories:1900,protein:140,carbs:210,fat:63,stepsGoal:15000},meals:[],workouts:[],body:[],steps:[],lastWorkout:[],syncMeta:{profileUpdatedAt:'',lastWorkoutUpdatedAt:'',deleted:{meals:{},workouts:{},body:{},steps:{}}},settings:{apiUrl:GIFT.apiUrl||'',apiToken:GIFT.apiToken||''}};
let db=normaliseDb(merge(DEFAULT,JSON.parse(localStorage.getItem('fitlog-v1')||'{}'))), selectedGroups=[], draftWorkout=[],syncTimer=null,syncing=false,syncAgain=false,changeCounter=0;db.settings={apiUrl:GIFT.apiUrl||db.settings.apiUrl||'',apiToken:GIFT.apiToken||db.settings.apiToken||''};
function merge(a,b){const o={...a,...b};for(const k of Object.keys(a))if(a[k]&&!Array.isArray(a[k])&&typeof a[k]==='object')o[k]={...a[k],...(b[k]||{})};return o}
function normaliseDb(value){value.syncMeta=value.syncMeta||{};value.syncMeta.deleted=value.syncMeta.deleted||{};for(const type of ['meals','workouts','body','steps']){value[type]=value[type]||[];value.syncMeta.deleted[type]=value.syncMeta.deleted[type]||{};value[type].forEach((x,i)=>{if(!x.id)x.id=type==='steps'?x.date:(x.time||`${x.date}-${i}`);if(!x.updatedAt)x.updatedAt=x.time||`${x.date||'1970-01-01'}T00:00:00.000Z`})}return value}
function cloudPayload(){const copy=JSON.parse(JSON.stringify(db));delete copy.settings;return copy}
function saveLocal(){localStorage.setItem('fitlog-v1',JSON.stringify(db));renderAll()}
function persist(){changeCounter++;saveLocal();clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncCloud(false),350)}
function markDeleted(type,key){db.syncMeta.deleted[type][key]=new Date().toISOString()}
async function syncCloud(showMessage=false){if(!db.settings.apiUrl)return;if(syncing){syncAgain=true;return}syncing=true;const startedAt=changeCounter;try{const merged=await sync('sync',{db:cloudPayload()});if(merged&&startedAt===changeCounter){const settings=db.settings;db=normaliseDb(merge(DEFAULT,merged));db.settings=settings;saveLocal()}else if(merged)syncAgain=true;if(showMessage)toast('所有裝置已同步')}catch(e){if(showMessage)toast('暫時未能同步，資料已保存在此裝置')}finally{syncing=false;if(syncAgain){syncAgain=false;setTimeout(()=>syncCloud(false),100)}}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function openSheet(title,html){$('#sheetTitle').textContent=title;$('#sheetContent').innerHTML=html;$('#sheetOverlay').classList.add('open');document.body.style.overflow='hidden'}
function closeSheet(){$('#sheetOverlay').classList.remove('open');document.body.style.overflow=''}
$('#closeSheet').onclick=closeSheet;$('#sheetOverlay').onclick=e=>{if(e.target.id==='sheetOverlay')closeSheet()};
function page(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id===name+'Page'));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));scrollTo({top:0,behavior:'smooth'});if(name==='training')renderWorkout();if(name==='progress')renderProgress(7)}
$$('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function todayMeals(){return db.meals.filter(x=>x.date===day())}function todayWorkouts(){return db.workouts.filter(x=>x.date===day())}
function totals(){return todayMeals().reduce((a,m)=>{a.calories+=+m.calories||0;a.protein+=+m.protein||0;a.carbs+=+m.carbs||0;a.fat+=+m.fat||0;return a},{calories:0,protein:0,carbs:0,fat:0})}
function renderAll(){
 const p=db.profile,t=totals(),steps=db.steps.find(x=>x.date===day())?.value||0,sets=todayWorkouts().reduce((n,w)=>n+w.exercises.reduce((s,e)=>s+e.sets.length,0),0);
 $('#todayDate').textContent=new Intl.DateTimeFormat('zh-HK',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
 $('#todayCalories').textContent=Math.round(t.calories).toLocaleString();$('#calorieGoal').textContent=(+p.calories||1900).toLocaleString();$('#calorieLeft').textContent=Math.max(0,(+p.calories||1900)-t.calories).toLocaleString();const pct=Math.min(100,Math.round(t.calories/(+p.calories||1900)*100));$('#caloriePercent').textContent=pct+'%';$('#calorieRing').style.setProperty('--percent',pct+'%');
 [['proteinNow',t.protein],['carbsNow',t.carbs],['fatNow',t.fat],['proteinGoal',p.protein||140],['carbsGoal',p.carbs||210],['fatGoal',p.fat||63]].forEach(([id,v])=>$('#'+id).textContent=Math.round(v));
 $('#todaySteps').textContent=(+steps).toLocaleString();$('#stepGoal').textContent=(+p.stepsGoal||15000).toLocaleString();$('#todaySets').textContent=sets+' Sets';$('#todayTrainingLabel').textContent=sets?todayWorkouts().map(w=>w.groups.join(' + ')).join(' · '):'未有訓練';
 renderMeals($('#todayMeals'),todayMeals());renderMeals($('#foodHistory'),todayMeals());renderWorkoutHistory();renderBodyHistory();
 $('#profileName').textContent=p.name||'未設定';$('#profileSummary').textContent=p.name?`減脂 · 每週訓練 ${p.trainingDays||0} 次`:'設定個人目標';$('#profileWeight').textContent=p.weight?`${(+p.weight).toFixed(1)} kg`:'—';$('#profileHeight').textContent=p.height?`${p.height} cm`:'—';$('#profileBodyFat').textContent=p.bodyFat?`${p.bodyFat}%`:'—';$('#profileMuscle').textContent=p.muscle?`${p.muscle} kg`:'—';$('#profileTarget').textContent=p.target?`${(+p.target).toFixed(1)} kg`:'—';$('#targetRemaining').textContent=p.weight&&p.target?`尚餘 ${Math.max(0,p.weight-p.target).toFixed(1)} kg`:'';$('#profileCalories').textContent=`${(+p.calories||1900).toLocaleString()} kcal`;$('#profileGoals').textContent=`Protein ${p.protein||140}g · ${(+p.stepsGoal||15000).toLocaleString()} 步`;
}
function renderMeals(root,meals){root.innerHTML=meals.length?meals.map(m=>`<div class="meal"><div><h3>${esc(m.type||'餐點')}</h3><p>${esc(m.items?.map(i=>i.name).join('、')||m.name)}</p><div class="tags"><span class="tag blue">P ${Math.round(m.protein)}g</span><span class="tag" style="color:var(--orange)">C ${Math.round(m.carbs)}g</span><span class="tag" style="color:var(--pink)">F ${Math.round(m.fat)}g</span></div></div><div class="entry-actions"><strong>${Math.round(m.calories)} kcal</strong><br><button class="delete-entry" data-delete-meal="${m.id}">刪除</button></div></div>`).join(''):'<div class="empty">尚未加入餐點</div>';$$('[data-delete-meal]').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢個食物紀錄？刪除後無法復原。'))return;markDeleted('meals',b.dataset.deleteMeal);db.meals=db.meals.filter(x=>x.id!==b.dataset.deleteMeal);persist();toast('食物紀錄已刪除')})}
function renderWorkoutHistory(){const root=$('#workoutHistory');if(!root)return;const list=todayWorkouts();root.innerHTML=list.length?list.map(w=>`<div class="history-row"><div><h3>${esc(w.groups.join(' + ')||'Training')}</h3><p>${w.exercises.reduce((n,e)=>n+e.sets.length,0)} Sets · ${(+w.volume||0).toLocaleString()} kg Volume</p></div><button class="delete-entry" data-delete-workout="${w.id}">刪除</button></div>`).join(''):'<div class="empty">今日未有已完成訓練</div>';$$('[data-delete-workout]').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢次 Workout？刪除後無法復原。'))return;markDeleted('workouts',b.dataset.deleteWorkout);db.workouts=db.workouts.filter(x=>x.id!==b.dataset.deleteWorkout);persist();toast('Workout 已刪除')})}
function renderBodyHistory(){const root=$('#bodyHistory');if(!root)return;const list=db.body.slice(-5).reverse();root.innerHTML=list.length?list.map((r,i)=>`<div class="history-row"><div><h3>${esc(r.date)} · ${(+r.weight||0).toFixed(1)} kg</h3><p>體脂 ${r.bodyFat||'—'}% · 骨骼肌 ${r.muscle||'—'} kg</p></div><button class="delete-entry" data-delete-body="${esc(r.id)}">刪除</button></div>`).join(''):'<div class="empty">未有身體紀錄</div>';$$('[data-delete-body]').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢筆身體紀錄？刪除後無法復原。'))return;markDeleted('body',b.dataset.deleteBody);db.body=db.body.filter(x=>x.id!==b.dataset.deleteBody);const latest=db.body.at(-1);if(latest)Object.assign(db.profile,{weight:latest.weight,bodyFat:latest.bodyFat,muscle:latest.muscle});db.syncMeta.profileUpdatedAt=new Date().toISOString();persist();toast('身體紀錄已刪除')})}

$('#stepsCard').onclick=()=>{const current=db.steps.find(x=>x.date===day())?.value||0;openSheet('今日步數',`<div class="form-row"><label>步數</label><input class="control" id="stepsInput" type="number" inputmode="numeric" value="${current}"></div><div class="chips">${[5000,8000,10000,15000].map(n=>`<button class="chip step-preset" data-value="${n}">${n.toLocaleString()}</button>`).join('')}</div><button class="primary" id="saveSteps">儲存步數</button>${current?'<button class="danger-link" id="deleteSteps">刪除今日步數</button>':''}`);$$('.step-preset').forEach(b=>b.onclick=()=>$('#stepsInput').value=b.dataset.value);$('#saveSteps').onclick=()=>{const value=Math.max(0,+$('#stepsInput').value||0),i=db.steps.findIndex(x=>x.date===day()),updatedAt=new Date().toISOString();if(i>=0)Object.assign(db.steps[i],{value,updatedAt});else db.steps.push({id:day(),date:day(),value,updatedAt});delete db.syncMeta.deleted.steps[day()];persist();closeSheet();toast('步數已更新')};if($('#deleteSteps'))$('#deleteSteps').onclick=()=>{if(!confirm('確定刪除今日步數？刪除後無法復原。'))return;markDeleted('steps',day());db.steps=db.steps.filter(x=>x.date!==day());persist();closeSheet();toast('今日步數已刪除')}};

$('#chooseFood').onclick=()=>$('#foodFile').click();$('#foodFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;openSheet('分析食物','<div class="empty">分析中…</div>');try{const base64=await resizeImage(f);const result=await analyzeFood(base64);showFoodReview(result,base64)}catch(err){closeSheet();toast('分析失敗，請改用手動新增')}finally{$('#foodFile').value=''}};
$('#manualMeal').onclick=()=>showFoodReview({mealType:'餐點',items:[{name:'自訂食物',cookingMethod:'',portion:'1份',oil:'不確定',calories:0,protein:0,carbs:0,fat:0}],confidence:'manual'},'');
function resizeImage(file){return new Promise((resolve,reject)=>{const img=new Image,reader=new FileReader;reader.onerror=reject;reader.onload=()=>img.src=reader.result;img.onload=()=>{const max=1024,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72).split(',')[1])};reader.readAsDataURL(file)})}
async function analyzeFood(base64){if(!db.settings.apiUrl)return {mealType:'午餐',items:[{name:'香煎雞胸',cookingMethod:'香煎',portion:'160g',oil:'少油',calories:265,protein:45,carbs:0,fat:9},{name:'白飯',cookingMethod:'蒸煮',portion:'1碗',oil:'無油',calories:220,protein:4,carbs:53,fat:1},{name:'西蘭花',cookingMethod:'灼',portion:'100g',oil:'無油',calories:35,protein:3,carbs:7,fat:0}],confidence:'demo'};return sync('analyzeFood',{imageBase64:base64,mimeType:'image/jpeg'})}
function showFoodReview(r,base64){const items=r.items||[];openSheet('確認分析結果',`${base64?`<img class="preview" src="data:image/jpeg;base64,${base64}" alt="餐點預覽">`:''}<div class="form-row"><label>餐別</label><select class="control" id="mealType"><option>早餐</option><option ${r.mealType==='午餐'?'selected':''}>午餐</option><option>晚餐</option><option>小食</option><option>運動後餐</option></select></div><div id="foodEditor">${items.map((i,n)=>foodEditor(i,n)).join('')}</div><button class="secondary" id="appendFood">＋ 新增食物</button><div class="summary" id="mealSummary"></div><button class="primary" id="saveMeal">確認並儲存</button>`);bindFoodEditor();updateMealSummary();$('#appendFood').onclick=()=>{$('#foodEditor').insertAdjacentHTML('beforeend',foodEditor({name:'新食物',portion:'1份',cookingMethod:'',oil:'不確定',calories:0,protein:0,carbs:0,fat:0},$$('.food-item').length));bindFoodEditor();updateMealSummary()};$('#saveMeal').onclick=saveMeal}
function foodEditor(i,n){return `<div class="food-item"><div class="food-item-head"><b>食物 ${n+1}</b><button class="danger-link remove-food" style="width:auto;margin:0">刪除</button></div><div class="form-grid"><div class="form-row full"><label>食物名稱</label><input class="control food-name" value="${esc(i.name)}"></div><div class="form-row"><label>份量</label><input class="control food-portion" value="${esc(i.portion)}"></div><div class="form-row"><label>煮法</label><input class="control food-method" value="${esc(i.cookingMethod)}"></div><div class="form-row"><label>用油</label><select class="control food-oil">${['無油','少油','正常','多油','不確定'].map(x=>`<option ${x===i.oil?'selected':''}>${x}</option>`).join('')}</select></div><div class="form-row"><label>實際食用</label><select class="control food-ratio"><option value="1">全部</option><option value=".75">¾</option><option value=".5">一半</option><option value=".25">¼</option></select></div>${['calories','protein','carbs','fat'].map(k=>`<div class="form-row"><label>${k==='calories'?'kcal':k[0].toUpperCase()}</label><input class="control food-${k}" type="number" value="${+i[k]||0}"></div>`).join('')}</div></div>`}
function bindFoodEditor(){$$('.food-item input,.food-item select').forEach(x=>x.oninput=updateMealSummary);$$('.remove-food').forEach(b=>b.onclick=()=>{b.closest('.food-item').remove();updateMealSummary()})}
function collectFood(){return $$('.food-item').map(el=>{const ratio=+el.querySelector('.food-ratio').value;return {name:el.querySelector('.food-name').value,portion:el.querySelector('.food-portion').value,cookingMethod:el.querySelector('.food-method').value,oil:el.querySelector('.food-oil').value,ratio,...Object.fromEntries(['calories','protein','carbs','fat'].map(k=>[k,(+el.querySelector('.food-'+k).value||0)*ratio]))}})}
function updateMealSummary(){const t=collectFood().reduce((a,i)=>{for(const k of ['calories','protein','carbs','fat'])a[k]+=i[k];return a},{calories:0,protein:0,carbs:0,fat:0});$('#mealSummary').innerHTML=`<span>本餐估算</span><strong>${Math.round(t.calories)} kcal</strong><small>P ${Math.round(t.protein)}g · C ${Math.round(t.carbs)}g · F ${Math.round(t.fat)}g</small>`}
function saveMeal(){const items=collectFood(),t=items.reduce((a,i)=>{for(const k of ['calories','protein','carbs','fat'])a[k]+=i[k];return a},{calories:0,protein:0,carbs:0,fat:0}),now=new Date().toISOString();db.meals.push({id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,type:$('#mealType').value,items,...t});persist();closeSheet();toast('餐點已儲存')}

const GROUPS=['Chest','Back','Shoulders','Legs','Glutes','Arms','Core','Full Body','Cardio'];$('#muscleGroups').innerHTML=GROUPS.map(g=>`<button class="chip" data-group="${g}">${g}</button>`).join('');$$('#muscleGroups .chip').forEach(b=>b.onclick=()=>{b.classList.toggle('on');selectedGroups=$$('#muscleGroups .chip.on').map(x=>x.dataset.group);renderWorkout()});
function renderWorkout(){$('#workoutTitle').textContent=selectedGroups.length?selectedGroups.join(' + '):'今日訓練';$('#workoutExercises').innerHTML=draftWorkout.map((e,i)=>`<div class="exercise" data-i="${i}"><div class="exercise-head"><h3>${esc(e.name).toUpperCase()}</h3><button class="remove-ex">刪除</button></div>${e.sets.map((s,n)=>`<div class="set-row"><span>${n+1}</span><input class="set-weight" type="number" value="${s.weight}" aria-label="重量 kg"><input class="set-reps" type="number" value="${s.reps}" aria-label="次數 reps"><button class="set-check ${s.done?'done':''}">✓</button></div>`).join('')}<button class="add-set">＋ Add Set</button></div>`).join('');$$('.remove-ex').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢個動作及所有 Sets？'))return;draftWorkout.splice(+b.closest('.exercise').dataset.i,1);renderWorkout()});$$('.add-set').forEach(b=>b.onclick=()=>{draftWorkout[+b.closest('.exercise').dataset.i].sets.push({weight:0,reps:10,done:false});renderWorkout()});$$('.set-check').forEach(b=>b.onclick=()=>{const box=b.closest('.exercise'),row=b.closest('.set-row'),ei=+box.dataset.i,si=[...box.querySelectorAll('.set-row')].indexOf(row);draftWorkout[ei].sets[si].done=!draftWorkout[ei].sets[si].done;renderWorkout()});$$('.set-weight,.set-reps').forEach(inp=>inp.onchange=()=>{const box=inp.closest('.exercise'),row=inp.closest('.set-row'),ei=+box.dataset.i,si=[...box.querySelectorAll('.set-row')].indexOf(row);draftWorkout[ei].sets[si][inp.classList.contains('set-weight')?'weight':'reps']=+inp.value||0})}
$('#addExercise').onclick=()=>{const matches=window.FITLOG_EXERCISES.filter(e=>!selectedGroups.length||e.groups.some(g=>selectedGroups.includes(g)));openSheet('新增動作',`<input class="control" id="exerciseSearch" placeholder="搜尋動作"><div id="exerciseList">${exerciseChoices(matches)}</div><button class="secondary" id="customExercise">＋ 自訂動作</button>`);$('#exerciseSearch').oninput=e=>$('#exerciseList').innerHTML=exerciseChoices(matches.filter(x=>x.name.toLowerCase().includes(e.target.value.toLowerCase())));bindExerciseChoices();$('#customExercise').onclick=()=>{const name=prompt('動作名稱');if(name){draftWorkout.push({name,groups:selectedGroups,sets:[{weight:0,reps:10,done:false}]});closeSheet();renderWorkout()}}};
function exerciseChoices(list){return list.map((e,i)=>`<button class="choice exercise-choice" data-name="${esc(e.name)}"><b>${esc(e.name).toUpperCase()}</b><span>${esc(e.groups.join(' · '))} · ${esc(e.equipment)}</span></button>`).join('')||'<div class="empty">沒有符合嘅動作</div>'}
function bindExerciseChoices(){$$('.exercise-choice').forEach(b=>b.onclick=()=>{const e=window.FITLOG_EXERCISES.find(x=>x.name===b.dataset.name);draftWorkout.push({name:e.name,groups:e.groups,sets:[{weight:0,reps:10,done:false}]});closeSheet();renderWorkout()})}
$('#reuseWorkout').onclick=()=>{draftWorkout=JSON.parse(JSON.stringify(db.lastWorkout||[]));if(!draftWorkout.length)toast('未有上次訓練');else{selectedGroups=[...new Set(draftWorkout.flatMap(e=>e.groups))];$$('#muscleGroups .chip').forEach(b=>b.classList.toggle('on',selectedGroups.includes(b.dataset.group)));renderWorkout();toast('已沿用上次訓練')}};
$('#finishWorkout').onclick=()=>{if(!draftWorkout.length)return toast('請先新增動作');const sets=draftWorkout.reduce((n,e)=>n+e.sets.length,0),volume=draftWorkout.reduce((n,e)=>n+e.sets.reduce((s,x)=>s+(+x.weight||0)*(+x.reps||0),0),0),now=new Date().toISOString();db.workouts.push({id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,groups:selectedGroups,exercises:JSON.parse(JSON.stringify(draftWorkout)),volume});db.lastWorkout=JSON.parse(JSON.stringify(draftWorkout));db.syncMeta.lastWorkoutUpdatedAt=now;persist();openSheet('完成訓練',`<div class="summary"><span>WORK DONE.</span><strong>${sets} SETS</strong><small>${esc(selectedGroups.join(' + ')||'TRAINING')} · ${volume.toLocaleString()} KG VOLUME</small></div><button class="primary" id="doneWorkout">返回今日</button>`);$('#doneWorkout').onclick=()=>{draftWorkout=[];selectedGroups=[];closeSheet();page('today')}};

$('#editProfile').onclick=()=>profileForm();function profileForm(){const p=db.profile;openSheet('編輯個人資料',`<div class="form-grid">${field('name','暱稱',p.name,'text','full')}${field('birthYear','出生年份',p.birthYear,'number')}${selectField('sex','生理性別',p.sex,['','男性','女性'])}${field('height','身高（cm）',p.height)}${field('trainingDays','每週訓練次數',p.trainingDays)}${field('weight','目前體重（kg）',p.weight,'number','')}${field('target','目標體重（kg）',p.target)}${field('bodyFat','體脂率（%）',p.bodyFat)}${field('muscle','骨骼肌量（kg）',p.muscle)}${field('calories','每日熱量',p.calories)}${field('protein','Protein（g）',p.protein)}${field('carbs','Carbs（g）',p.carbs)}${field('fat','Fat（g）',p.fat)}${field('stepsGoal','每日步數目標',p.stepsGoal,'number','full')}</div><button class="primary" id="saveProfile">儲存設定</button>`);$('#saveProfile').onclick=()=>{for(const k of Object.keys(p)){const el=$('#f-'+k);if(el)p[k]=['name','sex'].includes(k)?el.value:(+el.value||'')}const now=new Date().toISOString();db.syncMeta.profileUpdatedAt=now;if(p.weight)db.body.push({id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,weight:p.weight,bodyFat:p.bodyFat,muscle:p.muscle});persist();closeSheet();toast('個人設定已更新')}}
function field(id,label,value,type='number',cls=''){return `<div class="form-row ${cls}"><label>${label}</label><input class="control" id="f-${id}" type="${type}" step="0.1" value="${esc(value)}"></div>`}function selectField(id,label,value,opts){return `<div class="form-row"><label>${label}</label><select class="control" id="f-${id}">${opts.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select></div>`}
$('#logBody').onclick=()=>{const p=db.profile;openSheet('新增身體紀錄',`<div class="form-grid">${field('newWeight','體重（kg）',p.weight)}${field('newBodyFat','體脂率（%）',p.bodyFat)}${field('newMuscle','骨骼肌量（kg）',p.muscle,'number','full')}</div><button class="primary" id="saveBody">儲存紀錄</button>`);$('#saveBody').onclick=()=>{const now=new Date().toISOString(),r={id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,weight:+$('#f-newWeight').value||0,bodyFat:+$('#f-newBodyFat').value||0,muscle:+$('#f-newMuscle').value||0};db.body.push(r);Object.assign(db.profile,{weight:r.weight,bodyFat:r.bodyFat,muscle:r.muscle});db.syncMeta.profileUpdatedAt=now;persist();closeSheet();toast('身體紀錄已儲存')}};
$('#resetData').onclick=()=>{if(confirm('確定清除呢部裝置上嘅所有 FIT / LOG 資料？')){localStorage.removeItem('fitlog-v1');location.reload()}};
$('#restoreCloud').onclick=async()=>{if(!db.settings.apiUrl)return toast('請先設定後端 URL');await syncCloud(true)};

function renderProgress(days){const cutoff=new Date;cutoff.setDate(cutoff.getDate()-days+1);const body=db.body.filter(x=>new Date(x.date)>=cutoff),weights=body.map(x=>+x.weight).filter(Boolean),avg=weights.length?weights.reduce((a,b)=>a+b,0)/weights.length:0;$('#averageWeight').textContent=avg?avg.toFixed(1):'—';$('#weightChange').textContent=weights.length>1?`${weights.at(-1)-weights[0]<=0?'↓':'↑'} ${Math.abs(weights.at(-1)-weights[0]).toFixed(1)} kg`:'未有足夠紀錄';const dates=[...Array(Math.min(days,14))].map((_,i)=>{const d=new Date;d.setDate(d.getDate()-(Math.min(days,14)-1-i));return d.toISOString().slice(0,10)}),vals=dates.map(d=>db.steps.find(x=>x.date===d)?.value||0),max=Math.max(...vals,1);$('#stepsChart').innerHTML=vals.map(v=>`<div class="bar" style="height:${Math.max(2,v/max*100)}%" title="${v.toLocaleString()} 步"></div>`).join('');const proteinByDate={};db.meals.filter(x=>new Date(x.date)>=cutoff).forEach(m=>proteinByDate[m.date]=(proteinByDate[m.date]||0)+(+m.protein||0));const proteinDays=Object.values(proteinByDate).filter(v=>v>=(db.profile.protein||140)).length,workDates=new Set(db.workouts.filter(x=>new Date(x.date)>=cutoff).map(x=>x.date));$('#proteinDays').textContent=`${proteinDays} / ${days}`;$('#trainingDays').textContent=workDates.size}
$$('#rangeTabs button').forEach(b=>b.onclick=()=>{$$('#rangeTabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderProgress(+b.dataset.days)});
async function sync(action,payload){if(!db.settings.apiUrl)throw new Error('No API URL');const r=await fetch(db.settings.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:db.settings.apiToken,action,payload})});const data=await r.json();if(!data.ok)throw new Error(data.error||'Request failed');return data.data}
renderAll();syncCloud(false).then(()=>{if(!db.profile.name)setTimeout(profileForm,350)});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncCloud(false)});window.addEventListener('online',()=>syncCloud(false));
})();
