(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], day=()=>new Date().toISOString().slice(0,10);
const GIFT=window.FITLOG_CONFIG||{};
const DEFAULT={profile:{name:'',sex:'',birthYear:'',height:'',weight:'',target:'',bodyFat:'',muscle:'',trainingDays:4,calories:1900,protein:140,carbs:210,fat:63,stepsGoal:15000},meals:[],workouts:[],body:[],steps:[],lastWorkout:[],syncMeta:{profileUpdatedAt:'',lastWorkoutUpdatedAt:'',deleted:{meals:{},workouts:{},body:{},steps:{}}},settings:{apiUrl:GIFT.apiUrl||'',apiToken:GIFT.apiToken||''}};
let db=normaliseDb(merge(DEFAULT,JSON.parse(localStorage.getItem('fitlog-v1')||'{}'))), selectedGroups=[], draftWorkout=[],syncTimer=null,syncing=false,syncAgain=false,changeCounter=0;db.settings={apiUrl:GIFT.apiUrl||db.settings.apiUrl||'',apiToken:GIFT.apiToken||db.settings.apiToken||''};
function merge(a,b){const o={...a,...b};for(const k of Object.keys(a))if(a[k]&&!Array.isArray(a[k])&&typeof a[k]==='object')o[k]={...a[k],...(b[k]||{})};return o}
function normaliseDb(value){value.syncMeta=value.syncMeta||{};value.syncMeta.deleted=value.syncMeta.deleted||{};for(const type of ['meals','workouts','body','steps']){value[type]=value[type]||[];value.syncMeta.deleted[type]=value.syncMeta.deleted[type]||{};value[type].forEach((x,i)=>{if(!x.id)x.id=type==='steps'?x.date:(x.time||`${x.date}-${i}`);if(!x.updatedAt)x.updatedAt=x.time||`${x.date||'1970-01-01'}T00:00:00.000Z`})}return value}
function cloudPayload(){const copy=JSON.parse(JSON.stringify(db));delete copy.settings;return copy}
function saveLocal(){localStorage.setItem('fitlog-v1',JSON.stringify(db));renderAll()}
function persist(){changeCounter++;saveLocal();clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncCloud(false),350)}
function markDeleted(type,key){db.syncMeta.deleted[type][key]=new Date().toISOString()}
async function syncCloud(showMessage=false){if(!db.settings.apiUrl)return;if(syncing){syncAgain=true;return}syncing=true;const startedAt=changeCounter;try{const merged=await sync('sync',{db:cloudPayload()});if(merged&&startedAt===changeCounter){const settings=db.settings;db=normaliseDb(merge(DEFAULT,merged));db.settings=settings;saveLocal()}else if(merged)syncAgain=true;if(showMessage)toast('所有裝置已同步')}catch(e){if(showMessage)toast('暫時未能同步，資料已保存在此裝置')}finally{syncing=false;if(syncAgain){syncAgain=false;setTimeout(()=>syncCloud(false),100)}}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
let sheetEpoch=0;
function openSheet(title,html){sheetEpoch++;$('#sheetTitle').textContent=title;$('#sheetContent').innerHTML=html;$('#sheetOverlay').classList.add('open');document.body.style.overflow='hidden'}
function closeSheet(){sheetEpoch++;$('#sheetOverlay').classList.remove('open');document.body.style.overflow=''}
$('#closeSheet').onclick=closeSheet;
function page(name){$$('.page').forEach(p=>p.classList.toggle('active',p.id===name+'Page'));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));scrollTo({top:0,behavior:'smooth'});if(name==='training')renderWorkout();if(name==='progress')renderProgress(7)}
$$('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function todayMeals(){return db.meals.filter(x=>x.date===day())}function todayWorkouts(){return db.workouts.filter(x=>x.date===day())}
function totals(){return todayMeals().reduce((a,m)=>{a.calories+=+m.calories||0;a.protein+=+m.protein||0;a.carbs+=+m.carbs||0;a.fat+=+m.fat||0;return a},{calories:0,protein:0,carbs:0,fat:0})}
const MUSCLE_LABELS={Chest:'Chest',Back:'Back',Shoulders:'Shoulders',Legs:'Legs',Glutes:'Glutes',Arms:'Arms',Core:'Core','Full Body':'Full Body',Cardio:'Cardio'};
function workoutDates(){return [...new Set(db.workouts.map(w=>w.date).filter(Boolean))].sort()}
function workoutDayNumber(dateStr=day()){return workoutDates().filter(d=>d<=dateStr).length}
function workoutSummary(dateStr=day()){
 const workouts=db.workouts.filter(w=>w.date===dateStr),scores={},exercises=[];let sets=0,volume=0;
 workouts.forEach(w=>{volume+=+w.volume||0;(w.exercises||[]).forEach(e=>{const n=(e.sets||[]).length;sets+=n;exercises.push(e);const gs=(e.groups&&e.groups.length?e.groups:w.groups)||[];gs.forEach(g=>scores[g]=(scores[g]||0)+Math.max(1,n))})});
 const groups=Object.keys(scores).sort((a,b)=>scores[b]-scores[a]);return {date:dateStr,workouts,sets,volume,scores,groups,exercises}
}
function volumeLabel(v){v=+v||0;return v>=1000?`${(v/1000).toFixed(v>=10000?0:1)}T`:`${Math.round(v).toLocaleString()} KG`}
function burnEstimate(summary){const kg=+db.profile.weight||0;if(!kg||!summary.sets)return null;const mins=Math.max(20,Math.min(120,Math.round(summary.sets*2.3)));const calc=met=>met*3.5*kg/200*mins;let low=Math.round(calc(3.5)/10)*10,high=Math.round(calc(6)/10)*10;if(high<low)[low,high]=[high,low];return {low,high}}
function previousSimilarSummary(summary){if(!summary.groups.length)return null;const dates=workoutDates().filter(d=>d<summary.date).reverse();for(const d of dates){const s=workoutSummary(d);if(s.groups.some(g=>summary.groups.includes(g)))return s}return dates[0]?workoutSummary(dates[0]):null}
function comparisonHtml(summary){const prev=previousSimilarSummary(summary);if(!prev||(!summary.volume&&!prev.volume))return '';const diff=summary.volume-prev.volume,pct=prev.volume?Math.round(diff/prev.volume*100):null,setDiff=summary.sets-prev.sets;const sign=diff>0?'+':'';return `<div class="training-compare"><span>VS LAST SIMILAR DAY</span><b>${pct===null?'NEW BASELINE':`${sign}${pct}% VOLUME`}</b><small>${setDiff===0?'同樣 Sets':`${setDiff>0?'+':''}${setDiff} Sets`} · ${esc(prev.date)}</small></div>`}
function muscleFill(score,max){if(!score)return '#262b2e';const a=.32+.58*Math.min(1,score/Math.max(1,max));return `rgba(200,255,46,${a.toFixed(2)})`}
function muscleMapSvg(scores){
 const full=(scores['Full Body']||0)*.55,score=g=>(scores[g]||0)+full,max=Math.max(1,...['Chest','Back','Shoulders','Legs','Glutes','Arms','Core'].map(score));
 const f=g=>muscleFill(score(g),max),stroke='#4a5155',base='#1f2427';
 return `<svg class="muscle-map-svg" viewBox="0 0 300 245" role="img" aria-label="今日訓練肌群人體圖">
 <text x="75" y="232" text-anchor="middle">FRONT</text><text x="225" y="232" text-anchor="middle">BACK</text>
 <!-- front neutral --> <circle cx="75" cy="27" r="15" fill="${base}" stroke="${stroke}"/><rect x="69" y="41" width="12" height="10" rx="5" fill="${base}"/>
 <path d="M55 52 Q75 45 95 52 L101 112 Q91 126 75 127 Q59 126 49 112Z" fill="${base}" stroke="${stroke}"/>
 <ellipse cx="47" cy="62" rx="13" ry="10" fill="${f('Shoulders')}" stroke="${stroke}"/><ellipse cx="103" cy="62" rx="13" ry="10" fill="${f('Shoulders')}" stroke="${stroke}"/>
 <path d="M56 58 Q65 52 74 58 L73 79 Q63 82 55 75Z" fill="${f('Chest')}"/><path d="M76 58 Q85 52 94 58 L95 75 Q87 82 77 79Z" fill="${f('Chest')}"/>
 <rect x="62" y="81" width="26" height="39" rx="11" fill="${f('Core')}"/>
 <path d="M38 69 Q47 66 51 74 L46 123 Q42 135 33 128Z" fill="${f('Arms')}" stroke="${stroke}"/><path d="M112 69 Q103 66 99 74 L104 123 Q108 135 117 128Z" fill="${f('Arms')}" stroke="${stroke}"/>
 <path d="M55 121 Q66 116 73 125 L70 177 Q64 187 55 178Z" fill="${f('Legs')}" stroke="${stroke}"/><path d="M95 121 Q84 116 77 125 L80 177 Q86 187 95 178Z" fill="${f('Legs')}" stroke="${stroke}"/>
 <path d="M55 177 Q64 173 70 180 L67 215 Q60 222 54 214Z" fill="${f('Legs')}" stroke="${stroke}"/><path d="M95 177 Q86 173 80 180 L83 215 Q90 222 96 214Z" fill="${f('Legs')}" stroke="${stroke}"/>
 <!-- back --> <circle cx="225" cy="27" r="15" fill="${base}" stroke="${stroke}"/><rect x="219" y="41" width="12" height="10" rx="5" fill="${base}"/>
 <path d="M205 52 Q225 45 245 52 L251 112 Q241 126 225 127 Q209 126 199 112Z" fill="${f('Back')}" stroke="${stroke}"/>
 <ellipse cx="197" cy="62" rx="13" ry="10" fill="${f('Shoulders')}" stroke="${stroke}"/><ellipse cx="253" cy="62" rx="13" ry="10" fill="${f('Shoulders')}" stroke="${stroke}"/>
 <path d="M188 69 Q197 66 201 74 L196 123 Q192 135 183 128Z" fill="${f('Arms')}" stroke="${stroke}"/><path d="M262 69 Q253 66 249 74 L254 123 Q258 135 267 128Z" fill="${f('Arms')}" stroke="${stroke}"/>
 <ellipse cx="214" cy="122" rx="13" ry="12" fill="${f('Glutes')}"/><ellipse cx="236" cy="122" rx="13" ry="12" fill="${f('Glutes')}"/>
 <path d="M205 130 Q216 124 223 132 L220 177 Q214 187 205 178Z" fill="${f('Legs')}" stroke="${stroke}"/><path d="M245 130 Q234 124 227 132 L230 177 Q236 187 245 178Z" fill="${f('Legs')}" stroke="${stroke}"/>
 <path d="M205 177 Q214 173 220 180 L217 215 Q210 222 204 214Z" fill="${f('Legs')}" stroke="${stroke}"/><path d="M245 177 Q236 173 230 180 L233 215 Q240 222 246 214Z" fill="${f('Legs')}" stroke="${stroke}"/>
 </svg>`
}
function trainingResultHtml(summary){const burn=burnEstimate(summary),dayNo=workoutDayNumber(summary.date),groups=summary.groups.length?summary.groups.slice(0,4):['Training'];const chips=groups.map(g=>`<span class="muscle-chip">${esc(MUSCLE_LABELS[g]||g)}</span>`).join('');return `<div class="training-result">
 <div class="training-result-hero"><span>WORKOUT DAY</span><strong>${dayNo}</strong><b>${esc(groups.join(' + ').toUpperCase())}</b></div>
 <div class="training-result-stats"><div><b>${summary.sets}</b><small>SETS</small></div><div><b>${volumeLabel(summary.volume)}</b><small>VOLUME</small></div><div><b>${burn?`${burn.low}–${burn.high}`:'—'}</b><small>${burn?'KCAL · EST.':'ADD WEIGHT FOR BURN'}</small></div></div>
 <div class="muscle-map-card"><div class="training-card-title"><span>MUSCLES TRAINED</span><small>按今日動作及 Sets 顯示</small></div>${muscleMapSvg(summary.scores)}<div class="muscle-chips">${chips}</div></div>
 ${comparisonHtml(summary)}
 <p class="training-result-note">熱量只係粗略估算範圍；人體圖代表今日訓練涉及嘅肌群，唔代表即日增加咗幾多肌肉。</p>
 <button class="primary" id="trainingResultDone">返回今日</button></div>`}
function openTrainingResult(dateStr=day()){const s=workoutSummary(dateStr);if(!s.workouts.length){page('training');return}openSheet('Training Result',trainingResultHtml(s));$('#trainingResultDone').onclick=()=>{closeSheet();page('today')}}
function renderAll(){
 const p=db.profile,t=totals(),steps=db.steps.find(x=>x.date===day())?.value||0,training=workoutSummary(day()),burn=burnEstimate(training),done=training.workouts.length>0,dayNo=workoutDayNumber(day());
 $('#todayDate').textContent=new Intl.DateTimeFormat('zh-HK',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
 $('#todayCalories').textContent=Math.round(t.calories).toLocaleString();$('#calorieGoal').textContent=(+p.calories||1900).toLocaleString();$('#calorieLeft').textContent=Math.max(0,(+p.calories||1900)-t.calories).toLocaleString();const pct=Math.min(100,Math.round(t.calories/(+p.calories||1900)*100));$('#caloriePercent').textContent=pct+'%';$('#calorieRing').style.setProperty('--percent',pct+'%');
 [['proteinNow',t.protein],['carbsNow',t.carbs],['fatNow',t.fat],['proteinGoal',p.protein||140],['carbsGoal',p.carbs||210],['fatGoal',p.fat||63]].forEach(([id,v])=>$('#'+id).textContent=Math.round(v));
 $('#todaySteps').textContent=(+steps).toLocaleString();$('#stepGoal').textContent=(+p.stepsGoal||15000).toLocaleString();
 $('#workoutDayNumber').textContent=dayNo;$('#trainingCardEyebrow').textContent='WORKOUT DAY';$('#trainingCardAction').textContent=done?'RESULT ›':`LOG TODAY → DAY ${dayNo+1}`;
 $('#todayTrainingLabel').textContent=done?(training.groups.slice(0,3).join(' + ')||'TRAINING').toUpperCase():'今日未有訓練';$('#todayTrainingStats').textContent=done?`${training.sets} SETS · ${volumeLabel(training.volume)} VOLUME`:'完成今日訓練後會更新';$('#todayTrainingBurn').textContent=done&&burn?`EST. ${burn.low}–${burn.high} KCAL`:'';
 $('#trainingResultCard').classList.toggle('done',done);
 renderMeals($('#todayMeals'),todayMeals());renderMeals($('#foodHistory'),todayMeals());renderWorkoutHistory();renderBodyHistory();
 $('#profileName').textContent=p.name||'未設定';$('#profileSummary').textContent=p.name?`減脂 · 每週訓練 ${p.trainingDays||0} 次`:'設定個人目標';$('#profileWeight').textContent=p.weight?`${(+p.weight).toFixed(1)} kg`:'—';$('#profileHeight').textContent=p.height?`${p.height} cm`:'—';$('#profileBodyFat').textContent=p.bodyFat?`${p.bodyFat}%`:'—';$('#profileMuscle').textContent=p.muscle?`${p.muscle} kg`:'—';$('#profileTarget').textContent=p.target?`${(+p.target).toFixed(1)} kg`:'—';$('#targetRemaining').textContent=p.weight&&p.target?`尚餘 ${Math.max(0,p.weight-p.target).toFixed(1)} kg`:'';$('#profileCalories').textContent=`${(+p.calories||1900).toLocaleString()} kcal`;$('#profileGoals').textContent=`Protein ${p.protein||140}g · ${(+p.stepsGoal||15000).toLocaleString()} 步`;
}
function renderMeals(root,meals){root.innerHTML=meals.length?meals.map(m=>`<div class="meal"><div><h3>${esc(m.type||'餐點')}</h3><p>${esc(m.items?.map(i=>i.name).join('、')||m.name)}</p><div class="tags"><span class="tag blue">P ${Math.round(m.protein)}g</span><span class="tag" style="color:var(--orange)">C ${Math.round(m.carbs)}g</span><span class="tag" style="color:var(--pink)">F ${Math.round(m.fat)}g</span></div></div><div class="entry-actions"><strong>${Math.round(m.calories)} kcal</strong><br><button class="delete-entry" data-delete-meal="${m.id}">刪除</button></div></div>`).join(''):'<div class="empty">尚未加入餐點</div>';$$('[data-delete-meal]').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢個食物紀錄？刪除後無法復原。'))return;markDeleted('meals',b.dataset.deleteMeal);db.meals=db.meals.filter(x=>x.id!==b.dataset.deleteMeal);persist();toast('食物紀錄已刪除')})}
function renderWorkoutHistory(){const root=$('#workoutHistory');if(!root)return;const list=todayWorkouts();root.innerHTML=list.length?list.map(w=>`<div class="history-row"><div><h3>${esc(w.groups.join(' + ')||'Training')}</h3><p>${w.exercises.reduce((n,e)=>n+e.sets.length,0)} Sets · ${(+w.volume||0).toLocaleString()} kg Volume</p></div><button class="delete-entry" data-delete-workout="${w.id}">刪除</button></div>`).join(''):'<div class="empty">今日未有已完成訓練</div>';$$('[data-delete-workout]').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢次 Workout？刪除後無法復原。'))return;markDeleted('workouts',b.dataset.deleteWorkout);db.workouts=db.workouts.filter(x=>x.id!==b.dataset.deleteWorkout);persist();toast('Workout 已刪除')})}
function renderBodyHistory(){const root=$('#bodyHistory');if(!root)return;const list=db.body.slice(-5).reverse();root.innerHTML=list.length?list.map((r,i)=>`<div class="history-row"><div><h3>${esc(r.date)} · ${(+r.weight||0).toFixed(1)} kg</h3><p>體脂 ${r.bodyFat||'—'}% · 骨骼肌 ${r.muscle||'—'} kg</p></div><button class="delete-entry" data-delete-body="${esc(r.id)}">刪除</button></div>`).join(''):'<div class="empty">未有身體紀錄</div>';$$('[data-delete-body]').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢筆身體紀錄？刪除後無法復原。'))return;markDeleted('body',b.dataset.deleteBody);db.body=db.body.filter(x=>x.id!==b.dataset.deleteBody);const latest=db.body.at(-1);if(latest)Object.assign(db.profile,{weight:latest.weight,bodyFat:latest.bodyFat,muscle:latest.muscle});db.syncMeta.profileUpdatedAt=new Date().toISOString();persist();toast('身體紀錄已刪除')})}

$('#stepsCard').onclick=()=>{const current=db.steps.find(x=>x.date===day())?.value||0;openSheet('今日步數',`<div class="form-row"><label>步數（步）</label><input class="control" id="stepsInput" type="number" inputmode="numeric" value="${current}"></div><div class="chips">${[5000,8000,10000,15000].map(n=>`<button class="chip step-preset" data-value="${n}">${n.toLocaleString()} 步</button>`).join('')}</div><button class="primary" id="saveSteps">儲存步數</button>${current?'<button class="danger-link" id="deleteSteps">刪除今日步數</button>':''}`);$$('.step-preset').forEach(b=>b.onclick=()=>$('#stepsInput').value=b.dataset.value);$('#saveSteps').onclick=()=>{const value=Math.max(0,+$('#stepsInput').value||0),i=db.steps.findIndex(x=>x.date===day()),updatedAt=new Date().toISOString();if(i>=0)Object.assign(db.steps[i],{value,updatedAt});else db.steps.push({id:day(),date:day(),value,updatedAt});delete db.syncMeta.deleted.steps[day()];persist();closeSheet();toast('步數已更新')};if($('#deleteSteps'))$('#deleteSteps').onclick=()=>{if(!confirm('確定刪除今日步數？刪除後無法復原。'))return;markDeleted('steps',day());db.steps=db.steps.filter(x=>x.date!==day());persist();closeSheet();toast('今日步數已刪除')}};

$('#trainingResultCard').onclick=()=>{const s=workoutSummary(day());s.workouts.length?openTrainingResult(day()):page('training')};

function resizeImage(file){return new Promise((resolve,reject)=>{const img=new Image,reader=new FileReader;reader.onerror=reject;reader.onload=()=>img.src=reader.result;img.onload=()=>{const max=1024,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72).split(',')[1])};reader.readAsDataURL(file)})}
window.createFoodEntry({$,$$,esc,openSheet,closeSheet,toast,sync,day,resizeImage,getEpoch:()=>sheetEpoch,commit:meal=>{const now=new Date().toISOString();db.meals.push({...meal,id:crypto.randomUUID(),time:now,updatedAt:now});persist()}});

const GROUPS=['Chest','Back','Shoulders','Legs','Glutes','Arms','Core','Full Body','Cardio'];$('#muscleGroups').innerHTML=GROUPS.map(g=>`<button class="chip" data-group="${g}">${g}</button>`).join('');$$('#muscleGroups .chip').forEach(b=>b.onclick=()=>{b.classList.toggle('on');selectedGroups=$$('#muscleGroups .chip.on').map(x=>x.dataset.group);renderWorkout()});
function renderWorkout(){$('#workoutTitle').textContent=selectedGroups.length?selectedGroups.join(' + '):'今日訓練';$('#workoutExercises').innerHTML=draftWorkout.map((e,i)=>`<div class="exercise" data-i="${i}"><div class="exercise-head"><h3>${esc(e.name).toUpperCase()}</h3><button class="remove-ex">刪除</button></div>${e.sets.map((s,n)=>`<div class="set-row"><span>${n+1}</span><label class="set-field" ${e.metric==='duration'||e.metric==='seconds'?'style="visibility:hidden"':''}><small>重量（kg）</small><input class="set-weight" type="number" value="${s.weight}" aria-label="重量 kg" min="0" step="0.5"></label><label class="set-field"><small>${e.metric==='duration'?'時間（分鐘）':e.metric==='seconds'?'時間（秒）':'次數（下）'}</small><input class="set-reps" type="number" value="${s.reps}" aria-label="${e.metric==='duration'?'時間 分鐘':e.metric==='seconds'?'時間 秒':'次數 下'}" min="0" step="1"></label><button class="set-check ${s.done?'done':''}" aria-label="標記完成">✓</button></div>`).join('')}<button class="add-set">＋ 新增一組</button></div>`).join('');$$('.remove-ex').forEach(b=>b.onclick=()=>{if(!confirm('確定刪除呢個動作及所有 Sets？'))return;draftWorkout.splice(+b.closest('.exercise').dataset.i,1);renderWorkout()});$$('.add-set').forEach(b=>b.onclick=()=>{const ex=draftWorkout[+b.closest('.exercise').dataset.i];ex.sets.push({...ex.sets.at(-1),done:false});renderWorkout()});$$('.set-check').forEach(b=>b.onclick=()=>{const box=b.closest('.exercise'),row=b.closest('.set-row'),ei=+box.dataset.i,si=[...box.querySelectorAll('.set-row')].indexOf(row);draftWorkout[ei].sets[si].done=!draftWorkout[ei].sets[si].done;renderWorkout()});$$('.set-weight,.set-reps').forEach(inp=>inp.oninput=()=>{const box=inp.closest('.exercise'),row=inp.closest('.set-row'),ei=+box.dataset.i,si=[...box.querySelectorAll('.set-row')].indexOf(row);draftWorkout[ei].sets[si][inp.classList.contains('set-weight')?'weight':'reps']=+inp.value||0})}
$('#addExercise').onclick=()=>{const matches=window.FITLOG_EXERCISES.filter(e=>!selectedGroups.length||e.groups.some(g=>selectedGroups.includes(g)));openSheet('新增動作',`<input class="control" id="exerciseSearch" placeholder="搜尋動作"><div id="exerciseList">${exerciseChoices(matches)}</div><button class="secondary" id="customExercise">＋ 自訂動作</button>`);$('#exerciseSearch').oninput=e=>{$('#exerciseList').innerHTML=exerciseChoices(matches.filter(x=>x.name.toLowerCase().includes(e.target.value.toLowerCase())));bindExerciseChoices()};bindExerciseChoices();$('#customExercise').onclick=()=>{const name=prompt('動作名稱');if(name){draftWorkout.push({name,groups:selectedGroups,sets:[{weight:0,reps:8,done:false}]});closeSheet();renderWorkout()}}};
function exerciseChoices(list){return list.map((e,i)=>`<button class="choice exercise-choice" data-name="${esc(e.name)}"><b>${esc(e.name).toUpperCase()}</b><span>${esc(e.groups.join(' · '))} · ${esc(e.equipment)}</span></button>`).join('')||'<div class="empty">沒有符合嘅動作</div>'}
function bindExerciseChoices(){$$('.exercise-choice').forEach(b=>b.onclick=()=>{const e=window.FITLOG_EXERCISES.find(x=>x.name===b.dataset.name);draftWorkout.push({name:e.name,groups:e.groups,metric:e.metric||'reps',sets:[{weight:0,reps:e.metric?0:8,done:false}]});closeSheet();renderWorkout()})}
$('#reuseWorkout').onclick=()=>{draftWorkout=JSON.parse(JSON.stringify(db.lastWorkout||[]));if(!draftWorkout.length)toast('未有上次訓練');else{selectedGroups=[...new Set(draftWorkout.flatMap(e=>e.groups))];$$('#muscleGroups .chip').forEach(b=>b.classList.toggle('on',selectedGroups.includes(b.dataset.group)));renderWorkout();toast('已沿用上次訓練')}};
$('#finishWorkout').onclick=()=>{if(!draftWorkout.length)return toast('請先新增動作');const sets=draftWorkout.reduce((n,e)=>n+e.sets.length,0),volume=draftWorkout.reduce((n,e)=>n+(e.metric&&e.metric!=='reps'?0:e.sets.reduce((s,x)=>s+(+x.weight||0)*(+x.reps||0),0)),0),now=new Date().toISOString();db.workouts.push({id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,groups:selectedGroups,exercises:JSON.parse(JSON.stringify(draftWorkout)),volume});db.lastWorkout=JSON.parse(JSON.stringify(draftWorkout));db.syncMeta.lastWorkoutUpdatedAt=now;draftWorkout=[];selectedGroups=[];$$('#muscleGroups .chip').forEach(b=>b.classList.remove('on'));persist();openTrainingResult(day())};

$('#editProfile').onclick=()=>profileForm();function profileForm(){const p={...db.profile};openSheet('編輯個人資料',`<div class="form-grid">${field('name','暱稱',p.name,'text','full')}${field('birthYear','出生年份',p.birthYear,'number')}${selectField('sex','生理性別',p.sex,['','男性','女性'])}${field('height','身高（cm）',p.height)}${field('trainingDays','每週訓練（次）',p.trainingDays)}${field('weight','目前體重（kg）',p.weight,'number','')}${field('target','目標體重（kg）',p.target)}${field('bodyFat','體脂率（%）',p.bodyFat)}${field('muscle','骨骼肌量（kg）',p.muscle)}${field('calories','每日熱量（kcal）',p.calories)}${field('protein','Protein（g）',p.protein)}${field('carbs','Carbs（g）',p.carbs)}${field('fat','Fat（g）',p.fat)}${field('stepsGoal','每日步數目標（步）',p.stepsGoal,'number','full')}</div><button class="primary" id="saveProfile">儲存設定</button>`);$('#saveProfile').onclick=()=>{for(const k of Object.keys(p)){const el=$('#f-'+k);if(el)p[k]=['name','sex'].includes(k)?el.value:(+el.value||'')}const now=new Date().toISOString();db.profile=p;db.syncMeta.profileUpdatedAt=now;if(p.weight)db.body.push({id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,weight:p.weight,bodyFat:p.bodyFat,muscle:p.muscle});persist();closeSheet();toast('個人設定已更新')}}
function field(id,label,value,type='number',cls=''){return `<div class="form-row ${cls}"><label>${label}</label><input class="control" id="f-${id}" type="${type}" step="0.1" value="${esc(value)}"></div>`}function selectField(id,label,value,opts){return `<div class="form-row"><label>${label}</label><select class="control" id="f-${id}">${opts.map(x=>`<option ${x===value?'selected':''}>${x}</option>`).join('')}</select></div>`}
$('#logBody').onclick=()=>{const p=db.profile;openSheet('新增身體紀錄',`<div class="form-grid">${field('newWeight','體重（kg）',p.weight)}${field('newBodyFat','體脂率（%）',p.bodyFat)}${field('newMuscle','骨骼肌量（kg）',p.muscle,'number','full')}</div><button class="primary" id="saveBody">儲存紀錄</button>`);$('#saveBody').onclick=()=>{const now=new Date().toISOString(),r={id:crypto.randomUUID(),date:day(),time:now,updatedAt:now,weight:+$('#f-newWeight').value||0,bodyFat:+$('#f-newBodyFat').value||0,muscle:+$('#f-newMuscle').value||0};db.body.push(r);Object.assign(db.profile,{weight:r.weight,bodyFat:r.bodyFat,muscle:r.muscle});db.syncMeta.profileUpdatedAt=now;persist();closeSheet();toast('身體紀錄已儲存')}};
$('#resetData').onclick=()=>{if(confirm('確定清除呢部裝置上嘅所有 FIT / LOG 資料？')){localStorage.removeItem('fitlog-v1');location.reload()}};
$('#restoreCloud').onclick=async()=>{if(!db.settings.apiUrl)return toast('請先設定後端 URL');await syncCloud(true)};

function renderProgress(days){const cutoff=new Date;cutoff.setDate(cutoff.getDate()-days+1);const body=db.body.filter(x=>new Date(x.date)>=cutoff),weights=body.map(x=>+x.weight).filter(Boolean),avg=weights.length?weights.reduce((a,b)=>a+b,0)/weights.length:0;$('#averageWeight').textContent=avg?avg.toFixed(1):'—';$('#weightChange').textContent=weights.length>1?`${weights.at(-1)-weights[0]<=0?'↓':'↑'} ${Math.abs(weights.at(-1)-weights[0]).toFixed(1)} kg`:'未有足夠紀錄';const dates=[...Array(Math.min(days,14))].map((_,i)=>{const d=new Date;d.setDate(d.getDate()-(Math.min(days,14)-1-i));return d.toISOString().slice(0,10)}),vals=dates.map(d=>db.steps.find(x=>x.date===d)?.value||0),max=Math.max(...vals,1);$('#stepsChart').innerHTML=vals.map(v=>`<div class="bar" style="height:${Math.max(2,v/max*100)}%" title="${v.toLocaleString()} 步"></div>`).join('');const proteinByDate={};db.meals.filter(x=>new Date(x.date)>=cutoff).forEach(m=>proteinByDate[m.date]=(proteinByDate[m.date]||0)+(+m.protein||0));const proteinDays=Object.values(proteinByDate).filter(v=>v>=(db.profile.protein||140)).length,workDates=new Set(db.workouts.filter(x=>new Date(x.date)>=cutoff).map(x=>x.date));$('#proteinDays').textContent=`${proteinDays} / ${days}`;$('#trainingDays').textContent=workDates.size}
$$('#rangeTabs button').forEach(b=>b.onclick=()=>{$$('#rangeTabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderProgress(+b.dataset.days)});
async function sync(action,payload){if(!db.settings.apiUrl)throw new Error('No API URL');const r=await fetch(db.settings.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:db.settings.apiToken,action,payload})});const data=await r.json();if(!data.ok)throw new Error(data.error||'Request failed');return data.data}
renderAll();syncCloud(false);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncCloud(false)});window.addEventListener('online',()=>syncCloud(false));
})();
