window.FITLOG_EXERCISES = [
  {name:'Bench Press',groups:['Chest','Triceps'],equipment:'Barbell'},
  {name:'Incline Bench Press',groups:['Chest','Shoulders','Triceps'],equipment:'Barbell'},
  {name:'Dumbbell Bench Press',groups:['Chest','Triceps'],equipment:'Dumbbell'},
  {name:'Incline Dumbbell Press',groups:['Chest','Shoulders'],equipment:'Dumbbell'},
  {name:'Chest Press',groups:['Chest','Triceps'],equipment:'Machine'},
  {name:'Chest Fly',groups:['Chest'],equipment:'Machine'},
  {name:'Cable Fly',groups:['Chest'],equipment:'Cable'},
  {name:'Push-up',groups:['Chest','Triceps','Core'],equipment:'Bodyweight'},
  {name:'Pull-up',groups:['Back','Biceps'],equipment:'Bodyweight'},
  {name:'Lat Pulldown',groups:['Back','Biceps'],equipment:'Cable'},
  {name:'Seated Cable Row',groups:['Back','Biceps'],equipment:'Cable'},
  {name:'Bent-over Row',groups:['Back','Biceps'],equipment:'Barbell'},
  {name:'One-arm Dumbbell Row',groups:['Back','Biceps'],equipment:'Dumbbell'},
  {name:'T-bar Row',groups:['Back'],equipment:'Machine'},
  {name:'Straight-arm Pulldown',groups:['Back'],equipment:'Cable'},
  {name:'Deadlift',groups:['Back','Legs','Glutes','Core'],equipment:'Barbell'},
  {name:'Shoulder Press',groups:['Shoulders','Triceps'],equipment:'Machine'},
  {name:'Dumbbell Shoulder Press',groups:['Shoulders','Triceps'],equipment:'Dumbbell'},
  {name:'Arnold Press',groups:['Shoulders','Triceps'],equipment:'Dumbbell'},
  {name:'Lateral Raise',groups:['Shoulders'],equipment:'Dumbbell'},
  {name:'Cable Lateral Raise',groups:['Shoulders'],equipment:'Cable'},
  {name:'Front Raise',groups:['Shoulders'],equipment:'Dumbbell'},
  {name:'Rear Delt Fly',groups:['Shoulders','Back'],equipment:'Machine'},
  {name:'Face Pull',groups:['Shoulders','Back'],equipment:'Cable'},
  {name:'Upright Row',groups:['Shoulders'],equipment:'Barbell'},
  {name:'Barbell Squat',groups:['Legs','Glutes','Core'],equipment:'Barbell'},
  {name:'Front Squat',groups:['Legs','Core'],equipment:'Barbell'},
  {name:'Goblet Squat',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Leg Press',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Walking Lunges',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Reverse Lunges',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Bulgarian Split Squat',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Romanian Deadlift',groups:['Legs','Glutes','Back'],equipment:'Barbell'},
  {name:'Leg Extension',groups:['Legs'],equipment:'Machine'},
  {name:'Leg Curl',groups:['Legs'],equipment:'Machine'},
  {name:'Calf Raise',groups:['Legs'],equipment:'Machine'},
  {name:'Hip Thrust',groups:['Glutes','Legs'],equipment:'Barbell'},
  {name:'Glute Bridge',groups:['Glutes','Core'],equipment:'Bodyweight'},
  {name:'Cable Kickback',groups:['Glutes'],equipment:'Cable'},
  {name:'Hip Abduction',groups:['Glutes'],equipment:'Machine'},
  {name:'Step-up',groups:['Glutes','Legs'],equipment:'Dumbbell'},
  {name:'Biceps Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Hammer Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Preacher Curl',groups:['Arms'],equipment:'Machine'},
  {name:'Cable Curl',groups:['Arms'],equipment:'Cable'},
  {name:'Triceps Pushdown',groups:['Arms'],equipment:'Cable'},
  {name:'Overhead Triceps Extension',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Skull Crusher',groups:['Arms'],equipment:'Barbell'},
  {name:'Bench Dip',groups:['Arms','Chest'],equipment:'Bodyweight'},
  {name:'Plank',groups:['Core'],equipment:'Bodyweight'},
  {name:'Crunch',groups:['Core'],equipment:'Bodyweight'},
  {name:'Leg Raise',groups:['Core'],equipment:'Bodyweight'},
  {name:'Russian Twist',groups:['Core'],equipment:'Bodyweight'},
  {name:'Cable Crunch',groups:['Core'],equipment:'Cable'},
  {name:'Ab Wheel Rollout',groups:['Core'],equipment:'Other'},
  {name:'Mountain Climber',groups:['Core','Full Body'],equipment:'Bodyweight'},
  {name:'Burpee',groups:['Full Body'],equipment:'Bodyweight'},
  {name:'Kettlebell Swing',groups:['Full Body','Glutes'],equipment:'Kettlebell'},
  {name:'Thruster',groups:['Full Body','Shoulders','Legs'],equipment:'Dumbbell'},
  {name:'Farmer’s Carry',groups:['Full Body','Core','Arms'],equipment:'Dumbbell'},
  {name:'Treadmill',groups:['Cardio'],equipment:'Machine',metric:'duration'},
  {name:'Stair Climber',groups:['Cardio','Legs'],equipment:'Machine',metric:'duration'},
  {name:'Stationary Bike',groups:['Cardio','Legs'],equipment:'Machine',metric:'duration'},
  {name:'Rowing Machine',groups:['Cardio','Back','Full Body'],equipment:'Machine',metric:'duration'}
];
