window.FITLOG_EXERCISES = [
  {name:'Bench Press',groups:['Chest','Triceps'],equipment:'Barbell'},
  {name:'Incline Bench Press',groups:['Chest','Shoulders','Triceps'],equipment:'Barbell'},
  {name:'Dumbbell Bench Press',groups:['Chest','Triceps'],equipment:'Dumbbell'},
  {name:'Incline Dumbbell Press',groups:['Chest','Shoulders'],equipment:'Dumbbell'},
  {name:'Chest Press',groups:['Chest','Triceps'],equipment:'Machine'},
  {name:'Chest Fly',groups:['Chest'],equipment:'Machine'},
  {name:'Cable Fly',groups:['Chest'],equipment:'Cable'},
  {name:'Push-up',groups:['Chest','Triceps','Core'],equipment:'Bodyweight'},
  {name:'Pull-up',groups:['Back','Biceps'],equipment:'Bodyweight'},
  {name:'Lat Pulldown',groups:['Back','Biceps'],equipment:'Cable'},
  {name:'Seated Cable Row',groups:['Back','Biceps'],equipment:'Cable'},
  {name:'Bent-over Row',groups:['Back','Biceps'],equipment:'Barbell'},
  {name:'One-arm Dumbbell Row',groups:['Back','Biceps'],equipment:'Dumbbell'},
  {name:'T-bar Row',groups:['Back'],equipment:'Machine'},
  {name:'Straight-arm Pulldown',groups:['Back'],equipment:'Cable'},
  {name:'Deadlift',groups:['Back','Legs','Glutes','Core'],equipment:'Barbell'},
  {name:'Shoulder Press',groups:['Shoulders','Triceps'],equipment:'Machine'},
  {name:'Dumbbell Shoulder Press',groups:['Shoulders','Triceps'],equipment:'Dumbbell'},
  {name:'Arnold Press',groups:['Shoulders','Triceps'],equipment:'Dumbbell'},
  {name:'Lateral Raise',groups:['Shoulders'],equipment:'Dumbbell'},
  {name:'Cable Lateral Raise',groups:['Shoulders'],equipment:'Cable'},
  {name:'Front Raise',groups:['Shoulders'],equipment:'Dumbbell'},
  {name:'Rear Delt Fly',groups:['Shoulders','Back'],equipment:'Machine'},
  {name:'Face Pull',groups:['Shoulders','Back'],equipment:'Cable'},
  {name:'Upright Row',groups:['Shoulders'],equipment:'Barbell'},
  {name:'Barbell Squat',groups:['Legs','Glutes','Core'],equipment:'Barbell'},
  {name:'Front Squat',groups:['Legs','Core'],equipment:'Barbell'},
  {name:'Goblet Squat',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Leg Press',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Walking Lunges',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Reverse Lunges',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Bulgarian Split Squat',groups:['Legs','Glutes'],equipment:'Dumbbell'},
  {name:'Romanian Deadlift',groups:['Legs','Glutes','Back'],equipment:'Barbell'},
  {name:'Leg Extension',groups:['Legs'],equipment:'Machine'},
  {name:'Leg Curl',groups:['Legs'],equipment:'Machine'},
  {name:'Calf Raise',groups:['Legs'],equipment:'Machine'},
  {name:'Hip Thrust',groups:['Glutes','Legs'],equipment:'Barbell'},
  {name:'Glute Bridge',groups:['Glutes','Core'],equipment:'Bodyweight'},
  {name:'Cable Kickback',groups:['Glutes'],equipment:'Cable'},
  {name:'Hip Abduction',groups:['Glutes'],equipment:'Machine'},
  {name:'Step-up',groups:['Glutes','Legs'],equipment:'Dumbbell'},
  {name:'Biceps Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Hammer Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Preacher Curl',groups:['Arms'],equipment:'Machine'},
  {name:'Cable Curl',groups:['Arms'],equipment:'Cable'},
  {name:'Triceps Pushdown',groups:['Arms'],equipment:'Cable'},
  {name:'Overhead Triceps Extension',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Skull Crusher',groups:['Arms'],equipment:'Barbell'},
  {name:'Bench Dip',groups:['Arms','Chest'],equipment:'Bodyweight'},
  {name:'Plank',groups:['Core'],equipment:'Bodyweight',metric:'seconds'},
  {name:'Crunch',groups:['Core'],equipment:'Bodyweight'},
  {name:'Leg Raise',groups:['Core'],equipment:'Bodyweight'},
  {name:'Russian Twist',groups:['Core'],equipment:'Bodyweight'},
  {name:'Cable Crunch',groups:['Core'],equipment:'Cable'},
  {name:'Ab Wheel Rollout',groups:['Core'],equipment:'Other'},
  {name:'Mountain Climber',groups:['Core','Full Body'],equipment:'Bodyweight'},
  {name:'Burpee',groups:['Full Body'],equipment:'Bodyweight'},
  {name:'Kettlebell Swing',groups:['Full Body','Glutes'],equipment:'Kettlebell'},
  {name:'Thruster',groups:['Full Body','Shoulders','Legs'],equipment:'Dumbbell'},
  {name:'Farmer’s Carry',groups:['Full Body','Core','Arms'],equipment:'Dumbbell'},
  {name:'Treadmill',groups:['Cardio'],equipment:'Machine',metric:'duration'},
  {name:'Stair Climber',groups:['Cardio','Legs'],equipment:'Machine',metric:'duration'},
  {name:'Stationary Bike',groups:['Cardio','Legs'],equipment:'Machine',metric:'duration'},
  {name:'Rowing Machine',groups:['Cardio','Back','Full Body'],equipment:'Machine',metric:'duration'}
];

// Charles Glass demonstrations: Muscle & Strength's Training Fundamentals series.
// Chest: https://www.muscleandstrength.com/videos/training-fundamentals-charles-glass-chest
// Shoulders: https://www.muscleandstrength.com/videos/training-fundamentals-charles-glass-shoulders
// Legs: https://www.muscleandstrength.com/videos/training-fundamentals-charles-glass-legs
// Remaining entries are general exercise variants, not attributed to a coach.
window.FITLOG_EXERCISES.push(
  {name:'Decline Bench Press',groups:['Chest','Arms'],equipment:'Barbell'},
  {name:'Rear Delt Cable Fly',groups:['Shoulders','Back'],equipment:'Cable'},
  {name:'Hack Squat',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Deficit Stiff-legged Deadlift',groups:['Legs','Glutes','Back'],equipment:'Barbell'},
  {name:'Decline Dumbbell Press',groups:['Chest'],equipment:'Dumbbell'},
  {name:'Smith Machine Incline Press',groups:['Chest','Shoulders'],equipment:'Smith Machine'},
  {name:'Low-to-high Cable Fly',groups:['Chest'],equipment:'Cable'},
  {name:'High-to-low Cable Fly',groups:['Chest'],equipment:'Cable'},
  {name:'Incline Dumbbell Fly',groups:['Chest'],equipment:'Dumbbell'},
  {name:'Dumbbell Pullover',groups:['Chest','Back'],equipment:'Dumbbell'},
  {name:'Chest Dip',groups:['Chest','Arms'],equipment:'Bodyweight'},
  {name:'Reverse-grip Lat Pulldown',groups:['Back','Arms'],equipment:'Cable'},
  {name:'Neutral-grip Lat Pulldown',groups:['Back','Arms'],equipment:'Cable'},
  {name:'Wide-grip Lat Pulldown',groups:['Back','Arms'],equipment:'Cable'},
  {name:'Single-arm Cable Row',groups:['Back','Arms'],equipment:'Cable'},
  {name:'Chest-supported Dumbbell Row',groups:['Back','Arms'],equipment:'Dumbbell'},
  {name:'Machine High Row',groups:['Back'],equipment:'Machine'},
  {name:'Meadows Row',groups:['Back'],equipment:'Landmine'},
  {name:'Machine Pullover',groups:['Back'],equipment:'Machine'},
  {name:'Seated Dumbbell Lateral Raise',groups:['Shoulders'],equipment:'Dumbbell'},
  {name:'Leaning Cable Lateral Raise',groups:['Shoulders'],equipment:'Cable'},
  {name:'Behind-the-back Cable Lateral Raise',groups:['Shoulders'],equipment:'Cable'},
  {name:'Incline Bench Rear Delt Fly',groups:['Shoulders','Back'],equipment:'Dumbbell'},
  {name:'Machine Lateral Raise',groups:['Shoulders'],equipment:'Machine'},
  {name:'Single-arm Landmine Press',groups:['Shoulders','Chest'],equipment:'Landmine'},
  {name:'Smith Machine Shoulder Press',groups:['Shoulders','Arms'],equipment:'Smith Machine'},
  {name:'Dumbbell Shrug',groups:['Back','Shoulders'],equipment:'Dumbbell'},
  {name:'Pendulum Squat',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Smith Machine Squat',groups:['Legs','Glutes'],equipment:'Smith Machine'},
  {name:'Single-leg Press',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Narrow-stance Leg Press',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Wide-stance Leg Press',groups:['Legs','Glutes'],equipment:'Machine'},
  {name:'Seated Leg Curl',groups:['Legs'],equipment:'Machine'},
  {name:'Lying Leg Curl',groups:['Legs'],equipment:'Machine'},
  {name:'Standing Single-leg Curl',groups:['Legs'],equipment:'Machine'},
  {name:'Seated Calf Raise',groups:['Legs'],equipment:'Machine'},
  {name:'Leg Press Calf Raise',groups:['Legs'],equipment:'Machine'},
  {name:'Hip Adduction',groups:['Legs'],equipment:'Machine'},
  {name:'Smith Machine Hip Thrust',groups:['Glutes','Legs'],equipment:'Smith Machine'},
  {name:'Cable Pull-through',groups:['Glutes','Legs'],equipment:'Cable'},
  {name:'Single-leg Romanian Deadlift',groups:['Glutes','Legs'],equipment:'Dumbbell'},
  {name:'45-degree Back Extension',groups:['Back','Glutes','Legs'],equipment:'Bodyweight'},
  {name:'Incline Dumbbell Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Spider Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Bayesian Cable Curl',groups:['Arms'],equipment:'Cable'},
  {name:'EZ-bar Curl',groups:['Arms'],equipment:'EZ Bar'},
  {name:'Reverse Curl',groups:['Arms'],equipment:'EZ Bar'},
  {name:'Concentration Curl',groups:['Arms'],equipment:'Dumbbell'},
  {name:'Rope Triceps Pushdown',groups:['Arms'],equipment:'Cable'},
  {name:'Single-arm Cable Triceps Extension',groups:['Arms'],equipment:'Cable'},
  {name:'Overhead Cable Triceps Extension',groups:['Arms'],equipment:'Cable'},
  {name:'Close-grip Bench Press',groups:['Arms','Chest'],equipment:'Barbell'},
  {name:'Hanging Knee Raise',groups:['Core'],equipment:'Bodyweight'},
  {name:'Pallof Press',groups:['Core'],equipment:'Cable'},
  {name:'Side Plank',groups:['Core'],equipment:'Bodyweight',metric:'seconds'},
  {name:'Elliptical',groups:['Cardio'],equipment:'Machine',metric:'duration'}
);
